Dposse
Raven-s-Eye-Solutions/class-introduction-template pull request #20
Opened 2020-09-13 19:37 UTC by dposse

Added my about page, check it out?

2020-09-13 20:48 UTC, ravens-eye requested changes, later dismissed
Looks good! Just remove the npm lockfile cause we're using Yarn and should be good to go!

2020-09-13 20:48 UTC, ravens-eye commented on client/assets/css/dan.css
> +* Copyright (c) 2020 Animate.css*/:root{--animate-duration:1s;--animate-delay:1s;--animate-repeat:1}.animated{animation-duration:1s;animation-duration:var(--animate-duration);animation-fill-mode:both
It's best to load in normalize from a CDN, aggressive cache policy, better speed and all that.

2020-09-13 20:48 UTC, ravens-eye commented on client/assets/css/dan.css
> +* Copyright (c) 2020 Animate.css*/:root{--animate-duration:1s;--animate-delay:1s;--animate-repeat:1}.animated{animation-duration:1s;animation-duration:var(--animate-duration);animation-fill-mode:both
Several options here: https://classic.yarnpkg.com/en/package/normalize.css

2020-09-13 20:48 UTC, ravens-eye commented on client/dan.html
> +        silly CORS
See this for fastest quick and dirty CORS workaround: https://github.com/izuzak/urlreq

See an example of how I've used it in the past: https://www.karstenrabe.dev/#github-scraper-code

2020-09-13 20:49 UTC, ravens-eye commented
I see now you're using Hugo... Not familiar with it and realize that normalize may be bundled with that ? Not sure. Would love to learn more

2020-09-14 03:06 UTC, krab7191 approved these changes

2020-09-14 03:07 UTC, merged